### PR TITLE
handle ping and respond with pong

### PR DESCRIPTION
**Pull request by fiatjaf**
I don't know if this works, but it compiles.

the problem is that my client sends PINGs automatically to search.nos.today and gets a bunch of notices back.

### CODE REVIEW

**Comment by darashi** [comment]
Thank you for the patch!

When applied, the NOTICE no longer returns as expected, but it seems to return the Pong twice.

Before:

```
❯ wscat -P --slash -c wss://search.nos.today
Connected (press CTRL+C to quit)
> /ping
< Received pong (data: "")
< ["NOTICE","Error: non-text message Ping([])"]
> 
```

After:

```
❯ wscat -P --slash -c ws://localhost:3000   
Connected (press CTRL+C to quit)
> /ping
< Received pong (data: "")
< Received pong (data: "")
```

Looking again, I see that Pong is already being returned from [search.nos.today](http://search.nos.today/). Axum does this, according to https://docs.rs/axum/latest/axum/extract/ws/enum.Message.html#variant.Ping . So the problem seemed to be returning the extra NOTICE.

We can just ignore pings here, and this seems to be working:

```
❯ wscat -P --slash -c ws://localhost:3000
Connected (press CTRL+C to quit)
> /ping
< Received pong (data: "")
```

**Comment by darashi** [comment]
Now I'm going to deploy to search.nos.today

**Comment by darashi** [comment]
Now it seems to be working as expected. Does this work for you? 

```
❯ wscat -P --slash -c wss://search.nos.today
Connected (press CTRL+C to quit)
> /ping
< Received pong (data: "")
```

I'm really glad to have you look at this :sparkles:

**Comment by fiatjaf** [comment]
Yes, thank you!

**Pull request merged**
